// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telephony_lookup_proto_file.proto

package com.android.libcore.timezone.telephonylookup.proto;

public final class TelephonyLookupProtoFile {
  private TelephonyLookupProtoFile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TelephonyLookupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.android.libcore.timezone.telephonylookup.proto.TelephonyLookup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
     */
    java.util.List<com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network> 
        getNetworksList();
    /**
     * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
     */
    com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network getNetworks(int index);
    /**
     * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
     */
    int getNetworksCount();
    /**
     * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
     */
    java.util.List<? extends com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.NetworkOrBuilder> 
        getNetworksOrBuilderList();
    /**
     * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
     */
    com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.NetworkOrBuilder getNetworksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.android.libcore.timezone.telephonylookup.proto.TelephonyLookup}
   */
  public static final class TelephonyLookup extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.android.libcore.timezone.telephonylookup.proto.TelephonyLookup)
      TelephonyLookupOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TelephonyLookup.newBuilder() to construct.
    private TelephonyLookup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TelephonyLookup() {
      networks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TelephonyLookup();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.internal_static_com_android_libcore_timezone_telephonylookup_proto_TelephonyLookup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.internal_static_com_android_libcore_timezone_telephonylookup_proto_TelephonyLookup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup.class, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup.Builder.class);
    }

    public static final int NETWORKS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network> networks_;
    /**
     * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network> getNetworksList() {
      return networks_;
    }
    /**
     * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.NetworkOrBuilder> 
        getNetworksOrBuilderList() {
      return networks_;
    }
    /**
     * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
     */
    @java.lang.Override
    public int getNetworksCount() {
      return networks_.size();
    }
    /**
     * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
     */
    @java.lang.Override
    public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network getNetworks(int index) {
      return networks_.get(index);
    }
    /**
     * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
     */
    @java.lang.Override
    public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.NetworkOrBuilder getNetworksOrBuilder(
        int index) {
      return networks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getNetworksCount(); i++) {
        if (!getNetworks(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < networks_.size(); i++) {
        output.writeMessage(1, networks_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < networks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, networks_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup)) {
        return super.equals(obj);
      }
      com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup other = (com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup) obj;

      if (!getNetworksList()
          .equals(other.getNetworksList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNetworksCount() > 0) {
        hash = (37 * hash) + NETWORKS_FIELD_NUMBER;
        hash = (53 * hash) + getNetworksList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.android.libcore.timezone.telephonylookup.proto.TelephonyLookup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.android.libcore.timezone.telephonylookup.proto.TelephonyLookup)
        com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.internal_static_com_android_libcore_timezone_telephonylookup_proto_TelephonyLookup_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.internal_static_com_android_libcore_timezone_telephonylookup_proto_TelephonyLookup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup.class, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup.Builder.class);
      }

      // Construct using com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (networksBuilder_ == null) {
          networks_ = java.util.Collections.emptyList();
        } else {
          networks_ = null;
          networksBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.internal_static_com_android_libcore_timezone_telephonylookup_proto_TelephonyLookup_descriptor;
      }

      @java.lang.Override
      public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup getDefaultInstanceForType() {
        return com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup.getDefaultInstance();
      }

      @java.lang.Override
      public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup build() {
        com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup buildPartial() {
        com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup result = new com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup result) {
        if (networksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            networks_ = java.util.Collections.unmodifiableList(networks_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.networks_ = networks_;
        } else {
          result.networks_ = networksBuilder_.build();
        }
      }

      private void buildPartial0(com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup) {
          return mergeFrom((com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup other) {
        if (other == com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup.getDefaultInstance()) return this;
        if (networksBuilder_ == null) {
          if (!other.networks_.isEmpty()) {
            if (networks_.isEmpty()) {
              networks_ = other.networks_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNetworksIsMutable();
              networks_.addAll(other.networks_);
            }
            onChanged();
          }
        } else {
          if (!other.networks_.isEmpty()) {
            if (networksBuilder_.isEmpty()) {
              networksBuilder_.dispose();
              networksBuilder_ = null;
              networks_ = other.networks_;
              bitField0_ = (bitField0_ & ~0x00000001);
              networksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNetworksFieldBuilder() : null;
            } else {
              networksBuilder_.addAllMessages(other.networks_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getNetworksCount(); i++) {
          if (!getNetworks(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network m =
                    input.readMessage(
                        com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.PARSER,
                        extensionRegistry);
                if (networksBuilder_ == null) {
                  ensureNetworksIsMutable();
                  networks_.add(m);
                } else {
                  networksBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network> networks_ =
        java.util.Collections.emptyList();
      private void ensureNetworksIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          networks_ = new java.util.ArrayList<com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network>(networks_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.Builder, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.NetworkOrBuilder> networksBuilder_;

      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public java.util.List<com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network> getNetworksList() {
        if (networksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(networks_);
        } else {
          return networksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public int getNetworksCount() {
        if (networksBuilder_ == null) {
          return networks_.size();
        } else {
          return networksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network getNetworks(int index) {
        if (networksBuilder_ == null) {
          return networks_.get(index);
        } else {
          return networksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public Builder setNetworks(
          int index, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network value) {
        if (networksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNetworksIsMutable();
          networks_.set(index, value);
          onChanged();
        } else {
          networksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public Builder setNetworks(
          int index, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.Builder builderForValue) {
        if (networksBuilder_ == null) {
          ensureNetworksIsMutable();
          networks_.set(index, builderForValue.build());
          onChanged();
        } else {
          networksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public Builder addNetworks(com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network value) {
        if (networksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNetworksIsMutable();
          networks_.add(value);
          onChanged();
        } else {
          networksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public Builder addNetworks(
          int index, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network value) {
        if (networksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNetworksIsMutable();
          networks_.add(index, value);
          onChanged();
        } else {
          networksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public Builder addNetworks(
          com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.Builder builderForValue) {
        if (networksBuilder_ == null) {
          ensureNetworksIsMutable();
          networks_.add(builderForValue.build());
          onChanged();
        } else {
          networksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public Builder addNetworks(
          int index, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.Builder builderForValue) {
        if (networksBuilder_ == null) {
          ensureNetworksIsMutable();
          networks_.add(index, builderForValue.build());
          onChanged();
        } else {
          networksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public Builder addAllNetworks(
          java.lang.Iterable<? extends com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network> values) {
        if (networksBuilder_ == null) {
          ensureNetworksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, networks_);
          onChanged();
        } else {
          networksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public Builder clearNetworks() {
        if (networksBuilder_ == null) {
          networks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          networksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public Builder removeNetworks(int index) {
        if (networksBuilder_ == null) {
          ensureNetworksIsMutable();
          networks_.remove(index);
          onChanged();
        } else {
          networksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.Builder getNetworksBuilder(
          int index) {
        return getNetworksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.NetworkOrBuilder getNetworksOrBuilder(
          int index) {
        if (networksBuilder_ == null) {
          return networks_.get(index);  } else {
          return networksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public java.util.List<? extends com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.NetworkOrBuilder> 
           getNetworksOrBuilderList() {
        if (networksBuilder_ != null) {
          return networksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(networks_);
        }
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.Builder addNetworksBuilder() {
        return getNetworksFieldBuilder().addBuilder(
            com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.getDefaultInstance());
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.Builder addNetworksBuilder(
          int index) {
        return getNetworksFieldBuilder().addBuilder(
            index, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.getDefaultInstance());
      }
      /**
       * <code>repeated .com.android.libcore.timezone.telephonylookup.proto.Network networks = 1;</code>
       */
      public java.util.List<com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.Builder> 
           getNetworksBuilderList() {
        return getNetworksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.Builder, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.NetworkOrBuilder> 
          getNetworksFieldBuilder() {
        if (networksBuilder_ == null) {
          networksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.Builder, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.NetworkOrBuilder>(
                  networks_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          networks_ = null;
        }
        return networksBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.android.libcore.timezone.telephonylookup.proto.TelephonyLookup)
    }

    // @@protoc_insertion_point(class_scope:com.android.libcore.timezone.telephonylookup.proto.TelephonyLookup)
    private static final com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup();
    }

    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TelephonyLookup>
        PARSER = new com.google.protobuf.AbstractParser<TelephonyLookup>() {
      @java.lang.Override
      public TelephonyLookup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TelephonyLookup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TelephonyLookup> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.TelephonyLookup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NetworkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.android.libcore.timezone.telephonylookup.proto.Network)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * A 3-digit numeric in ASCII. 
     * </pre>
     *
     * <code>required string mcc = 1;</code>
     * @return Whether the mcc field is set.
     */
    boolean hasMcc();
    /**
     * <pre>
     * A 3-digit numeric in ASCII. 
     * </pre>
     *
     * <code>required string mcc = 1;</code>
     * @return The mcc.
     */
    java.lang.String getMcc();
    /**
     * <pre>
     * A 3-digit numeric in ASCII. 
     * </pre>
     *
     * <code>required string mcc = 1;</code>
     * @return The bytes for mcc.
     */
    com.google.protobuf.ByteString
        getMccBytes();

    /**
     * <pre>
     * A 2- or 3-digit numeric in ASCII. 
     * </pre>
     *
     * <code>required string mnc = 2;</code>
     * @return Whether the mnc field is set.
     */
    boolean hasMnc();
    /**
     * <pre>
     * A 2- or 3-digit numeric in ASCII. 
     * </pre>
     *
     * <code>required string mnc = 2;</code>
     * @return The mnc.
     */
    java.lang.String getMnc();
    /**
     * <pre>
     * A 2- or 3-digit numeric in ASCII. 
     * </pre>
     *
     * <code>required string mnc = 2;</code>
     * @return The bytes for mnc.
     */
    com.google.protobuf.ByteString
        getMncBytes();

    /**
     * <pre>
     * An ISO 3166 alpha-2 code (lower case).  
     * </pre>
     *
     * <code>required string countryIsoCode = 3;</code>
     * @return Whether the countryIsoCode field is set.
     */
    boolean hasCountryIsoCode();
    /**
     * <pre>
     * An ISO 3166 alpha-2 code (lower case).  
     * </pre>
     *
     * <code>required string countryIsoCode = 3;</code>
     * @return The countryIsoCode.
     */
    java.lang.String getCountryIsoCode();
    /**
     * <pre>
     * An ISO 3166 alpha-2 code (lower case).  
     * </pre>
     *
     * <code>required string countryIsoCode = 3;</code>
     * @return The bytes for countryIsoCode.
     */
    com.google.protobuf.ByteString
        getCountryIsoCodeBytes();
  }
  /**
   * Protobuf type {@code com.android.libcore.timezone.telephonylookup.proto.Network}
   */
  public static final class Network extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.android.libcore.timezone.telephonylookup.proto.Network)
      NetworkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Network.newBuilder() to construct.
    private Network(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Network() {
      mcc_ = "";
      mnc_ = "";
      countryIsoCode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Network();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.internal_static_com_android_libcore_timezone_telephonylookup_proto_Network_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.internal_static_com_android_libcore_timezone_telephonylookup_proto_Network_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.class, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.Builder.class);
    }

    private int bitField0_;
    public static final int MCC_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mcc_ = "";
    /**
     * <pre>
     * A 3-digit numeric in ASCII. 
     * </pre>
     *
     * <code>required string mcc = 1;</code>
     * @return Whether the mcc field is set.
     */
    @java.lang.Override
    public boolean hasMcc() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * A 3-digit numeric in ASCII. 
     * </pre>
     *
     * <code>required string mcc = 1;</code>
     * @return The mcc.
     */
    @java.lang.Override
    public java.lang.String getMcc() {
      java.lang.Object ref = mcc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mcc_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * A 3-digit numeric in ASCII. 
     * </pre>
     *
     * <code>required string mcc = 1;</code>
     * @return The bytes for mcc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMccBytes() {
      java.lang.Object ref = mcc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mcc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MNC_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mnc_ = "";
    /**
     * <pre>
     * A 2- or 3-digit numeric in ASCII. 
     * </pre>
     *
     * <code>required string mnc = 2;</code>
     * @return Whether the mnc field is set.
     */
    @java.lang.Override
    public boolean hasMnc() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * A 2- or 3-digit numeric in ASCII. 
     * </pre>
     *
     * <code>required string mnc = 2;</code>
     * @return The mnc.
     */
    @java.lang.Override
    public java.lang.String getMnc() {
      java.lang.Object ref = mnc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mnc_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * A 2- or 3-digit numeric in ASCII. 
     * </pre>
     *
     * <code>required string mnc = 2;</code>
     * @return The bytes for mnc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMncBytes() {
      java.lang.Object ref = mnc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mnc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRYISOCODE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object countryIsoCode_ = "";
    /**
     * <pre>
     * An ISO 3166 alpha-2 code (lower case).  
     * </pre>
     *
     * <code>required string countryIsoCode = 3;</code>
     * @return Whether the countryIsoCode field is set.
     */
    @java.lang.Override
    public boolean hasCountryIsoCode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * An ISO 3166 alpha-2 code (lower case).  
     * </pre>
     *
     * <code>required string countryIsoCode = 3;</code>
     * @return The countryIsoCode.
     */
    @java.lang.Override
    public java.lang.String getCountryIsoCode() {
      java.lang.Object ref = countryIsoCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          countryIsoCode_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * An ISO 3166 alpha-2 code (lower case).  
     * </pre>
     *
     * <code>required string countryIsoCode = 3;</code>
     * @return The bytes for countryIsoCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryIsoCodeBytes() {
      java.lang.Object ref = countryIsoCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryIsoCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMcc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMnc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCountryIsoCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mcc_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mnc_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, countryIsoCode_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mcc_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mnc_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, countryIsoCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network)) {
        return super.equals(obj);
      }
      com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network other = (com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network) obj;

      if (hasMcc() != other.hasMcc()) return false;
      if (hasMcc()) {
        if (!getMcc()
            .equals(other.getMcc())) return false;
      }
      if (hasMnc() != other.hasMnc()) return false;
      if (hasMnc()) {
        if (!getMnc()
            .equals(other.getMnc())) return false;
      }
      if (hasCountryIsoCode() != other.hasCountryIsoCode()) return false;
      if (hasCountryIsoCode()) {
        if (!getCountryIsoCode()
            .equals(other.getCountryIsoCode())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMcc()) {
        hash = (37 * hash) + MCC_FIELD_NUMBER;
        hash = (53 * hash) + getMcc().hashCode();
      }
      if (hasMnc()) {
        hash = (37 * hash) + MNC_FIELD_NUMBER;
        hash = (53 * hash) + getMnc().hashCode();
      }
      if (hasCountryIsoCode()) {
        hash = (37 * hash) + COUNTRYISOCODE_FIELD_NUMBER;
        hash = (53 * hash) + getCountryIsoCode().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.android.libcore.timezone.telephonylookup.proto.Network}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.android.libcore.timezone.telephonylookup.proto.Network)
        com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.NetworkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.internal_static_com_android_libcore_timezone_telephonylookup_proto_Network_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.internal_static_com_android_libcore_timezone_telephonylookup_proto_Network_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.class, com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.Builder.class);
      }

      // Construct using com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        mcc_ = "";
        mnc_ = "";
        countryIsoCode_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.internal_static_com_android_libcore_timezone_telephonylookup_proto_Network_descriptor;
      }

      @java.lang.Override
      public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network getDefaultInstanceForType() {
        return com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.getDefaultInstance();
      }

      @java.lang.Override
      public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network build() {
        com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network buildPartial() {
        com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network result = new com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.mcc_ = mcc_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.mnc_ = mnc_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.countryIsoCode_ = countryIsoCode_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network) {
          return mergeFrom((com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network other) {
        if (other == com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network.getDefaultInstance()) return this;
        if (other.hasMcc()) {
          mcc_ = other.mcc_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasMnc()) {
          mnc_ = other.mnc_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasCountryIsoCode()) {
          countryIsoCode_ = other.countryIsoCode_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasMcc()) {
          return false;
        }
        if (!hasMnc()) {
          return false;
        }
        if (!hasCountryIsoCode()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                mcc_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                mnc_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                countryIsoCode_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object mcc_ = "";
      /**
       * <pre>
       * A 3-digit numeric in ASCII. 
       * </pre>
       *
       * <code>required string mcc = 1;</code>
       * @return Whether the mcc field is set.
       */
      public boolean hasMcc() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * A 3-digit numeric in ASCII. 
       * </pre>
       *
       * <code>required string mcc = 1;</code>
       * @return The mcc.
       */
      public java.lang.String getMcc() {
        java.lang.Object ref = mcc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mcc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * A 3-digit numeric in ASCII. 
       * </pre>
       *
       * <code>required string mcc = 1;</code>
       * @return The bytes for mcc.
       */
      public com.google.protobuf.ByteString
          getMccBytes() {
        java.lang.Object ref = mcc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mcc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * A 3-digit numeric in ASCII. 
       * </pre>
       *
       * <code>required string mcc = 1;</code>
       * @param value The mcc to set.
       * @return This builder for chaining.
       */
      public Builder setMcc(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mcc_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A 3-digit numeric in ASCII. 
       * </pre>
       *
       * <code>required string mcc = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMcc() {
        mcc_ = getDefaultInstance().getMcc();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A 3-digit numeric in ASCII. 
       * </pre>
       *
       * <code>required string mcc = 1;</code>
       * @param value The bytes for mcc to set.
       * @return This builder for chaining.
       */
      public Builder setMccBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        mcc_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object mnc_ = "";
      /**
       * <pre>
       * A 2- or 3-digit numeric in ASCII. 
       * </pre>
       *
       * <code>required string mnc = 2;</code>
       * @return Whether the mnc field is set.
       */
      public boolean hasMnc() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * A 2- or 3-digit numeric in ASCII. 
       * </pre>
       *
       * <code>required string mnc = 2;</code>
       * @return The mnc.
       */
      public java.lang.String getMnc() {
        java.lang.Object ref = mnc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mnc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * A 2- or 3-digit numeric in ASCII. 
       * </pre>
       *
       * <code>required string mnc = 2;</code>
       * @return The bytes for mnc.
       */
      public com.google.protobuf.ByteString
          getMncBytes() {
        java.lang.Object ref = mnc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mnc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * A 2- or 3-digit numeric in ASCII. 
       * </pre>
       *
       * <code>required string mnc = 2;</code>
       * @param value The mnc to set.
       * @return This builder for chaining.
       */
      public Builder setMnc(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mnc_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A 2- or 3-digit numeric in ASCII. 
       * </pre>
       *
       * <code>required string mnc = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMnc() {
        mnc_ = getDefaultInstance().getMnc();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A 2- or 3-digit numeric in ASCII. 
       * </pre>
       *
       * <code>required string mnc = 2;</code>
       * @param value The bytes for mnc to set.
       * @return This builder for chaining.
       */
      public Builder setMncBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        mnc_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object countryIsoCode_ = "";
      /**
       * <pre>
       * An ISO 3166 alpha-2 code (lower case).  
       * </pre>
       *
       * <code>required string countryIsoCode = 3;</code>
       * @return Whether the countryIsoCode field is set.
       */
      public boolean hasCountryIsoCode() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * An ISO 3166 alpha-2 code (lower case).  
       * </pre>
       *
       * <code>required string countryIsoCode = 3;</code>
       * @return The countryIsoCode.
       */
      public java.lang.String getCountryIsoCode() {
        java.lang.Object ref = countryIsoCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            countryIsoCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * An ISO 3166 alpha-2 code (lower case).  
       * </pre>
       *
       * <code>required string countryIsoCode = 3;</code>
       * @return The bytes for countryIsoCode.
       */
      public com.google.protobuf.ByteString
          getCountryIsoCodeBytes() {
        java.lang.Object ref = countryIsoCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryIsoCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * An ISO 3166 alpha-2 code (lower case).  
       * </pre>
       *
       * <code>required string countryIsoCode = 3;</code>
       * @param value The countryIsoCode to set.
       * @return This builder for chaining.
       */
      public Builder setCountryIsoCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        countryIsoCode_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * An ISO 3166 alpha-2 code (lower case).  
       * </pre>
       *
       * <code>required string countryIsoCode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountryIsoCode() {
        countryIsoCode_ = getDefaultInstance().getCountryIsoCode();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * An ISO 3166 alpha-2 code (lower case).  
       * </pre>
       *
       * <code>required string countryIsoCode = 3;</code>
       * @param value The bytes for countryIsoCode to set.
       * @return This builder for chaining.
       */
      public Builder setCountryIsoCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        countryIsoCode_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.android.libcore.timezone.telephonylookup.proto.Network)
    }

    // @@protoc_insertion_point(class_scope:com.android.libcore.timezone.telephonylookup.proto.Network)
    private static final com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network();
    }

    public static com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Network>
        PARSER = new com.google.protobuf.AbstractParser<Network>() {
      @java.lang.Override
      public Network parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Network> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Network> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.android.libcore.timezone.telephonylookup.proto.TelephonyLookupProtoFile.Network getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_android_libcore_timezone_telephonylookup_proto_TelephonyLookup_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_android_libcore_timezone_telephonylookup_proto_TelephonyLookup_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_android_libcore_timezone_telephonylookup_proto_Network_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_android_libcore_timezone_telephonylookup_proto_Network_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!telephony_lookup_proto_file.proto\0222com" +
      ".android.libcore.timezone.telephonylooku" +
      "p.proto\"`\n\017TelephonyLookup\022M\n\010networks\030\001" +
      " \003(\0132;.com.android.libcore.timezone.tele" +
      "phonylookup.proto.Network\";\n\007Network\022\013\n\003" +
      "mcc\030\001 \002(\t\022\013\n\003mnc\030\002 \002(\t\022\026\n\016countryIsoCode" +
      "\030\003 \002(\tB6\n2com.android.libcore.timezone.t" +
      "elephonylookup.protoP\000"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_android_libcore_timezone_telephonylookup_proto_TelephonyLookup_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_android_libcore_timezone_telephonylookup_proto_TelephonyLookup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_android_libcore_timezone_telephonylookup_proto_TelephonyLookup_descriptor,
        new java.lang.String[] { "Networks", });
    internal_static_com_android_libcore_timezone_telephonylookup_proto_Network_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_android_libcore_timezone_telephonylookup_proto_Network_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_android_libcore_timezone_telephonylookup_proto_Network_descriptor,
        new java.lang.String[] { "Mcc", "Mnc", "CountryIsoCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
